### ISSUE TITLE
Add an "Advanced" box in the converter's UI so the settings save path can be customized

### ISSUE THREAD

**Issue by MyNameIsTrez** [cortex-command-community/Cortex-Command-Legacy-Mod-Converter#11]
**Is your feature request related to a problem? Please describe.**
Have the path where the settings are saved be customizable in the converter's UI:
1. It lets people who want to keep their appdata folder under control have one less thing to worry about.
2. It means you can run things off of portable media (usb keys and stuff) and keep your settings (granted, this is a pretty unlikely use case).
3. It means that one could have different copies with different settings without any complicated effort.

**Describe the solution you'd like**
Add an "Advanced" box in the converter's UI for the "Settings save path" browser; it's good to have an advanced box for future-proofing reasons anyway. Have the settings save path set to the default path and make sure it's highlighted green by default. Give the settings save path a tooltip that tells the user they can leave it on the default path unless they really want to change it.

**Comment by garethyr** [comment]
Alternative to or in addition to customizing the path, it could default to the `.modconverter` folder that sits in the same directory as the exe.

**Comment by MyNameIsTrez** [comment]
I like the idea of always using the mod converter folder, that should remove unnecessary complexity for the user and will at least handle point one and two.
