### ISSUE TITLE
Case checking mismatches animation frames when a file with the same name exists

### ISSUE THREAD

**Issue by HeliumAnt** [cortex-command-community/Cortex-Command-Legacy-Mod-Converter#124]
**Describe the bug**
The case checking can mismatch animations when a file with same name as the animation exists, since the case checking routines don't know whether an animation is wanted or we're looking for the file literally

Example mod:

[orks.rte](https://cccp.old.mod.io/orks)

**Comment by MyNameIsTrez** [comment]
Since this was from the days when the mod converter engine was part of this repo, and was written in the Python version which used to do case checking, which the Zig version doesn't, I'll close this. Thanks for taking the time to create this issue regardless :)
