### ISSUE TITLE
Any mention of a mod's bmp should be edited so it refers to its new png path instead

### ISSUE THREAD

**Issue by MyNameIsTrez** [cortex-command-community/Cortex-Command-Legacy-Mod-Converter#42]

**Comment by SirJoshi** [comment]
I love how you're righting all of these issues even though your the only person who's going to fix them.

**Comment by MyNameIsTrez** [comment]
Haha, yeah I'm fully aware of that. It serves as a diary of some sort so I can look back on how productive my few weeks of vacation have been at a later date. It's also just because I have had so many things that needed to be done (this is issue 42 after all) that I simply forget what I wanted to do when I wake up otherwise. :)

**Comment by MyNameIsTrez** [comment]
Done: 9b67ad51b4ccb2a
