### ISSUE TITLE
MaxMass -> MaxInventoryMass for GI-251-mass-tooltips-for-buymenu

### ISSUE THREAD

**Issue by traunts** [cortex-command-community/Cortex-Command-Legacy-Mod-Converter#46]
Required to merge cortex-command-community/Cortex-Command-Community-Project-Source#274. 
All instances of `MaxMass` need to be replaced with `MaxInventoryMass`. This new property now no longer includes the craft's mass , so if possible the converter should display a warning so modders know that they need to subtract the craft's total mass from this val. 
I've gone over the Base files in a Data PR, however some Lua activity scripts that copy from them will have troubles, as they required manual cleanup. Any Lua that uses this property already accounts for the added mass, so will need to be converted by hand. 
Between the mass change and this Lua math change, this will require a lot of manual fixing.

**Comment by MyNameIsTrez** [comment]
Done
