### ISSUE TITLE
New Conversion Rules Part 2 [Wait a few days before add them]

### ISSUE THREAD

**Issue by MorgulUruk** [cortex-command-community/Cortex-Command-Legacy-Mod-Converter#58]
**For "Sounds.json":**

"Base.rte/Devices/Pistols/BlasterFire.flac": "Base.rte/Devices/Weapons/Pistol/Sounds/PistolFire.flac"
"Dummy.rte/Effects/Sounds/DestroyerFire.wav": "Dummy.rte/Devices/Weapons/Destroyer/Sounds/Fire1.flac",
"Browncoats.rte/Effects/Sounds/FlamerActive.wav": "Browncoats.rte/Devices/Weapons/Firestorm/Sounds/ProjectileLoop.flac",
"Coalition.rte/Effects/Sounds/PistolShot1a.wav": "Coalition.rte/Devices/Weapons/Pistol/Sounds/Fire1.flac",
"Base.rte/Actors/MetalBlunt2.flac": "Base.rte/Sounds/Physics/MetalBlunt1.flac",
"Base.rte/Actors/Crash1.flac": "Base.rte/Sounds/Physics/Crash1.flac",
"Coalition.rte/Effects/Sounds/PistolShot1a.wav": "Coalition.rte/Devices/Weapons/Pistol/Sounds/Fire1.flac",
"Imperatus.rte/Effects/Sounds/BigDogReloadStart.wav": "Imperatus.rte/Devices/Weapons/Bulldog/Sounds/ReloadStart.flac",
"Imperatus.rte/Effects/Sounds/BigDogReloadEnd.wav": "Imperatus.rte/Devices/Weapons/Bulldog/Sounds/ReloadEnd.flac",
"Imperatus.rte/Effects/Sounds/BigDogSpin.wav": "Imperatus.rte/Devices/Weapons/Bulldog/Sounds/SpinSound.flac",
"Ronin.rte/Effects/Sounds/BazookaFire.wav": "Ronin.rte/Devices/Weapons/RPG7/Sounds/Fire1.flac",

**For "Images.json":**

"Base.rte/Actors/Rockets/RocketLeg.png": "Base.rte/Craft/Shared/RocketLegA000.png",
"Base.rte/Actors/StorageCrate/CrateBodyA.png": "Base.rte/Craft/StorageCrate/CrateBodyA.png",
"Base.rte/Actors/StorageCrate/CrateRackFG.png": "Base.rte/Craft/StorageCrate/CrateBodyA.png",
"Base.rte/Actors/StorageCrate/CrateRackBG.png": "Base.rte/Craft/StorageCrate/CrateBodyA.png",
"Base.rte/Actors/StorageCrate/CrateRackMAT.png": "Base.rte/Craft/StorageCrate/CrateBodyA.png",
"Base.rte/Devices/Diggers/DiggerGibA.png": "Base.rte/Devices/Tools/Digger/Gibs/DiggerGibA.png",
"Browncoats.rte/Actors/Soldier/ArmBGA.bmp": "Browncoats.rte/Actors/Infantry/BrowncoatLight/ArmBGA.png",
"Browncoats.rte/Actors/Soldier/HandBGA.bmp": "Browncoats.rte/Actors/Infantry/BrowncoatLight/HandBGA.png",
"Base.rte/Effects/Pyro/Flashes/MuzzleFlash02.png": "Base.rte/Effects/Pyro/Flashes/MuzzleFlash02.png",
"Base.rte/Devices/Diggers/DiggerGibA.png": "Base.rte/Devices/Tools/Digger/Gibs/DiggerGibA.png",

**For "Misc.json":**

"Browncoat Fuel Bomb Burst": "Napalm Bomb Gib A",
"Dummy Turret Large Gib C": "Dummy Dreadnought Turret Gib C",
"FilePath = FilePath": "FilePath",
"\tPath = ": "\tFilePath = ",
"Rocket A Leg A": "Rocket Leg A",
"GibParticle = AEmitter\n\t\t\tCopyOf = Fuel Fire Trace Black": "GibParticle = PEmitter\n\t\t\tCopyOf = Fuel Fire Trace Black",
"Browncoat Soldier Hat Gib A": "Browncoat Light Soldier Hat Gib A",
"Browncoat Soldier Hat Gib B": "Browncoat Light Soldier Hat Gib B",
"Browncoat Soldier Hat Gib C": "Browncoat Light Soldier Hat Gib C",
"Browncoat Soldier Hat Gib D": "Browncoat Light Soldier Hat Gib D",
"Browncoat Soldier Hat Gib E": "Browncoat Light Soldier Hat Gib E",
"= Sound": "= SoundContainer",
"Flame 2 Hurt Emitter": "Flame 2 Hurt",
"Flame 1 Hurt Emitter": "Flame 1 Hurt",

**Comment by MyNameIsTrez** [comment]
Thank you! Merged them manually a while back
