### ISSUE TITLE
New Conversion Rules Part 3 [Wait until 8 April Before Add Those]

### ISSUE THREAD

**Issue by MorgulUruk** [cortex-command-community/Cortex-Command-Legacy-Mod-Converter#64]
**For "Image.json":**

"Dummy.rte/Devices/Sprites/PistolMagazineA.bmp": "Dummy.rte/Devices/Weapons/Nailgun/NailgunMagazine.png",
"Coalition.rte/Devices/Sprites/MagazineRocketA.bmp": "Browncoats.rte/Devices/Weapons/Stinger/StingerMagazine.png",

**For "Sounds.json":**

"Base.rte/Actors/ClankCrash.flac": "Base.rte/Sounds/Physics/ClankCrash.flac",
"Base.rte/Sounds/EmptyClick3.flac": "Base.rte/Sounds/Devices/EmptyClick1.flac",

**For "Misc.json":**

"Skeleton Jaw Gib A": "Skeleton Head Gib B",
"Soldier Helmet A": "Coalition Light Helmet",
"Block A": "Metal Block",
"Block B": "Concrete Block",
"Block H": "Tiny Block",
"Blood Liquid Mat": "Blood",
"Blood Sticky Mat": "Flesh",
"Blood Normal Mat": "Shelled Flesh",
"Enforcer Tiny Block": "Tiny Dummy Block",

**Comment by MyNameIsTrez** [comment]
Thank you! Merged them manually a while back
